connect 'jdbc:derby://localhost:1527/toppurbase;user=user;password=pass';

CREATE TABLE user (user_id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
					username VARCHAR(20) NOT NULL,
					password VARCHAR(20) NOT NULL,
					firstname VARCHAR(30),
					lastname VARCHAR(30),
					role VARCHAR(20) NOT NULL);

CREATE TABLE role (role VARCHAR(20) NOT NULL PRIMARY KEY);

CREATE TABLE department (department_id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
						department_name VARCHAR(50) NOT NULL);

CREATE TABLE pasient (pasient_id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1), 
						firstname VARCHAR(50)NOT NULL,
						lastname VARCHAR(50)NOT NULL,
						social_security_number VARCHAR(11) NOT NULL,
						picture blob(16M),
						department_id INT NOT NULL);

CREATE TABLE emergency_contact (emergency_contact_id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
								firstname VARCHAR(50) NOT NULL,
								lastname VARCHAR(50) NOT NULL,
								phone_number VARCHAR(15) NOT NULL
								pasient_id INT NOT NULL);

CREATE TABLE task (task_id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
					TIMESTAMP NOT NULL,
					dosage VARCHAR(20) NOT NULL,
					executed SMALLINT NOT NULL
					medicine_id INT NOT NULL,
					medicine_form VARCHAR(20) NOT NULL);

CREATE TABLE medicine(medicine_id INT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
						name VARCHAR(50));

CREATE TABLE medicine_form(form VARCHAR(20) NOT NULL PRIMARY KEY);

CREATE TABLE deviation(deviation_id INT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT 1)
						description VARCHAR(200) NOT NULL,
						timestamp,
						pasient_id INT NOT NULL);

ALTER TABLE user ADD CONSTRAINT role_fk FOREIGN KEY (role) REFERENCES role ON DELETE CASCADE;
ALTER TABLE patient ADD CONSTRAINT fk_postal_code FOREIGN KEY (postal_code) REFERENCES postal_address ON DELETE SET NULL;
ALTER TABLE patient ADD CONSTRAINT fk_bpid FOREIGN KEY (bpid) REFERENCES bedpost ON DELETE SET NULL;
ALTER TABLE bedpost ADD CONSTRAINT fk_did FOREIGN KEY (did) REFERENCES department ON DELETE CASCADE;
ALTER TABLE department ADD CONSTRAINT fk_cid FOREIGN KEY (cid) REFERENCES clinic ON DELETE CASCADE;

exit;