connect 'jdbc:derby://localhost:1527/toppurbase;user=user;password=pass';

CREATE TABLE user (user_id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
					username VARCHAR(20) NOT NULL,
					password VARCHAR(20) NOT NULL,
					firstname VARCHAR(30),
					lastname VARCHAR(30),
					role VARCHAR(20) NOT NULL);

CREATE TABLE role (role VARCHAR(20) NOT NULL PRIMARY KEY);

CREATE TABLE department (department_id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
						department_name VARCHAR(50) NOT NULL,
						clinic_name VARCHAR(50) NOT NULL);

CREATE TABLE department (did INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
						department_name VARCHAR(50) NOT NULL,
						cid INT NOT NULL);

CREATE TABLE bedpost (bpid INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1), bedpost_name VARCHAR(50)NOT NULL, did INT NOT NULL);

ALTER TABLE user ADD CONSTRAINT role_fk FOREIGN KEY (role) REFERENCES role ON DELETE CASCADE;
ALTER TABLE patient ADD CONSTRAINT fk_postal_code FOREIGN KEY (postal_code) REFERENCES postal_address ON DELETE SET NULL;
ALTER TABLE patient ADD CONSTRAINT fk_bpid FOREIGN KEY (bpid) REFERENCES bedpost ON DELETE SET NULL;
ALTER TABLE bedpost ADD CONSTRAINT fk_did FOREIGN KEY (did) REFERENCES department ON DELETE CASCADE;
ALTER TABLE department ADD CONSTRAINT fk_cid FOREIGN KEY (cid) REFERENCES clinic ON DELETE CASCADE;

exit;